### ISSUE TITLE
MVP Review

### ISSUE THREAD

**Issue by juliakim-ut** [simonpuno/spice#1]
#MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

### Comments
- [x] Map should be before Search (immediately after Business Page)
- [x] User can also limit their search results by location

Great Job!! Let me know if you have any questions!

**Comment by simonpuno** [comment]
Hi Julia, what is meant by this item: "The other 4 are from the MVP List or they have clarified them with you"?

**Comment by juliakim-ut** [comment]
Hi Simon!
I just left that checkbox empty for correction you need to make regarding comments I left.
MVP List looks good now! I will close this issue shortly. :)
