### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by juliakim-ut** [simonpuno/spice#2]
# Database Schema

- [x] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

### Comments
- [x] first name, last name, email, zipcode, and birthday(optional) fields are required upon sign up
- [x] Using 'text' data type will be better for Description, Content column in businesses table and reviews table respectively. There is a limit (255 characters) for a string type
- [x] businesses table requires Latitude and Longitude columns to integrate with map api
- [x] consider having city, zipcode columns for easier search implementation
- [x] can a business have multiple types?( e.g sushi, Japanese, asian) if so, consider adding `types` table and a `business_types`  joins table for a many to many relationship. :each business can fall into multiple types, and each type can apply to many businesses.
- [x] average rating for a business can be calculated by active record using association or sql query. In that case we dont need to have a column to save rating values in businesses table. This will make more sense once you finish benchBnB project.

**Comment by simonpuno** [comment]
Hi Julia, I've gotten most of the schema edits done. I am just a little confused on the second to last comment regarding a `types` table and `business_types` table. Would the `types` table only include one column called `type` where I would enter different types of business types? And would `business_types` table just include business `id` column and `type` column?

**Comment by juliakim-ut** [comment]
Types table will hold type as a string and business_types table will be a joins table between businesses and types holding business_id and type_id.
so business 'sushi Taku' can have many types( Japanese, sushi bars), type 'Japanese' can have many restaurants(sushi Taku, Kai Zan)

**Comment by juliakim-ut** [comment]
`types` `business_types` tables are missing 
- [x] Contains appropriate constraints/details
   - [x] primary key
   - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

* additional notes: you may consider having `cities` table to filter by city easy.

**Comment by simonpuno** [comment]
Hi Julia, these revisions have been made!

**Comment by juliakim-ut** [comment]
Since we made `types`, `cities` table, please modify corresponding columns in `businesses` table accordingly :)

**Comment by simonpuno** [comment]
Hi Julia, I changed `type` and `city` to `type_id` and `city_id` in the `businesses` table. Let me know if anything else needs editing. Thanks!

**Comment by juliakim-ut** [comment]
delete below unnecessary comments and add bullet points for foreign keys `city_id` and `type_id` and which table will these reference to ! and... you are good to go! 

`Type` will refer to type of business (ex: sushi, burger, etc.). Indexed for faster lookup when using search functionality.
`Rating` refers to star rating of restaurant. Not sure yet how I will use that integer to display stars on the screen.
Unsure about adding a column for reviews, but I don't think I need one. Reviews will be a separate table.

Excellent work! I am super excited to see your clone!

**Comment by simonpuno** [comment]
Done and done!
