### ISSUE TITLE
Routes Review

### ISSUE THREAD

**Issue by juliakim-ut** [simonpuno/spice#3]
# Backend Routes

- [x]  Contains the following sections: HTML, API Endpoints(Backend)
- [x]  Each route has a description
- [x]  API Endpoint routes contains wildcard variables written in `snake_case`
- [x]  Routes does not contain superfluous routes
- [x]  Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    -  probably doesn't need a `GET likes` api endpoint because that info comes through the post show

### Comments
- [x] business owners can create/update/delete their business can be bonus ('POST and PATCH actions in businesses). Yelp doesn't have the functionality of creating businesses as part of its CORE functionality.

# Frontend Routes

- [x]  Frontend routes contains wildcard variables written in `camelCase`
- [x]  Correctly formatted
    - [x]  Routes are displayed with inline coding text (backticks)

### Comments
- [x] will there be a functionality of editing review? if so, what is the route for it?
- [x] actual yelp site doesn't use modal for signup/login. Our goal is building pixel perfect clone! 😉

**Comment by simonpuno** [comment]
Think I got all of these done! Am I supposed to check them off myself in the list above or do you check them off once you've reviewed?
