### ISSUE TITLE
Sample State Review

### ISSUE THREAD

**Issue by juliakim-ut** [simonpuno/spice#4]
# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language `(```javascript...```)`. This will display the state as a code block instead of a giant line of text
    - [x]  Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka `comments` inside of `posts`
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can't change
            - like count and a boolean on whether the user likes the post instead of a likes slice

### Comments
- [x] use CamelCase for state's key
- [x] update to reflect changes to schema
- [x] you may want to have an array of review ids for each user in users slice instead of having userReviews slice in the state
	users: {
            1: {
                id: 1,
                firstName: "Simon",
                lastName: "Puno",
                reviews: [1,2,3]
            }
}

**Comment by simonpuno** [comment]
Hi Julia, these are all ready for a review! Thank you!

**Comment by simonpuno** [comment]
Hi Julia, I wanted to see your opinion on having a slice of state for `ui` that would hold the bounds for my map? I just got through that section in Benchbnb and they had us have a ui slice of state to hold any filters that the user applies to search feature. Please let me know your thoughts.

**Comment by juliakim-ut** [comment]
#Yes. You will need the slice of `filters` under the `ui` section.
`filter` slice can hold many filters that may limit your search results and map bounds can be one of them.
See attached screenshot from benchBnB live demo!

<img width="458" alt="Screen Shot 2021-09-02 at 8 58 26 PM" src="https://user-images.githubusercontent.com/59833955/131935138-b5ee7fd6-db92-41f2-bb66-b63094895a75.png">

**Comment by simonpuno** [comment]
Cool, just added a ui slice and filters slice within that. Thanks for the feedback!
